begin;
create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,nome text not null default 'Usuário',role text not null default 'viewer' check(role in('admin','viewer')),criado_em timestamptz default now(),atualizado_em timestamptz default now());
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.profiles where id=auth.uid() and role='admin')$$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,nome) values(new.id,coalesce(new.raw_user_meta_data->>'nome',split_part(new.email,'@',1))) on conflict do nothing;return new;end$$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create table if not exists public.fca_manifestos(id bigint generated always as identity primary key,contrato text not null,fato text not null,causa text not null,acao text not null,causa_raiz text not null,municipio text,manifesto text,data_criacao timestamptz not null default now(),usuario text not null,mes_referencia text not null,atualizado_em timestamptz default now());
create table if not exists public.fca_manifestos_audit(audit_id bigint generated always as identity primary key,fca_id bigint,operacao text,dados_anteriores jsonb,dados_novos jsonb,usuario uuid default auth.uid(),registrado_em timestamptz default now());
create index if not exists idx_fca_contrato on public.fca_manifestos(contrato);create index if not exists idx_fca_manifesto on public.fca_manifestos(manifesto);create index if not exists idx_fca_mes on public.fca_manifestos(mes_referencia);
create or replace function public.audit_fca() returns trigger language plpgsql security definer set search_path=public as $$begin if tg_op='INSERT' then insert into public.fca_manifestos_audit(fca_id,operacao,dados_novos) values(new.id,'INSERT',to_jsonb(new));return new;elsif tg_op='UPDATE' then new.atualizado_em=now();insert into public.fca_manifestos_audit(fca_id,operacao,dados_anteriores,dados_novos) values(new.id,'UPDATE',to_jsonb(old),to_jsonb(new));return new;else insert into public.fca_manifestos_audit(fca_id,operacao,dados_anteriores) values(old.id,'DELETE',to_jsonb(old));return old;end if;end$$;
drop trigger if exists fca_audit on public.fca_manifestos;create trigger fca_audit before insert or update or delete on public.fca_manifestos for each row execute procedure public.audit_fca();
alter table public.profiles enable row level security;alter table public.fca_manifestos enable row level security;alter table public.fca_manifestos_audit enable row level security;
drop policy if exists profiles_read on public.profiles;create policy profiles_read on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin());drop policy if exists fca_read on public.fca_manifestos;create policy fca_read on public.fca_manifestos for select to authenticated using(true);drop policy if exists fca_insert on public.fca_manifestos;create policy fca_insert on public.fca_manifestos for insert to authenticated with check(public.is_admin());drop policy if exists fca_update on public.fca_manifestos;create policy fca_update on public.fca_manifestos for update to authenticated using(public.is_admin()) with check(public.is_admin());drop policy if exists fca_delete on public.fca_manifestos;create policy fca_delete on public.fca_manifestos for delete to authenticated using(public.is_admin());drop policy if exists audit_read on public.fca_manifestos_audit;create policy audit_read on public.fca_manifestos_audit for select to authenticated using(public.is_admin());
grant select on public.profiles to authenticated;grant select,insert,update,delete on public.fca_manifestos to authenticated;grant usage,select on all sequences in schema public to authenticated;
insert into storage.buckets(id,name,public,file_size_limit) values('dados-operacionais','dados-operacionais',false,52428800) on conflict(id) do update set public=false;
drop policy if exists operational_read on storage.objects;create policy operational_read on storage.objects for select to authenticated using(bucket_id='dados-operacionais' and (storage.foldername(name))[1] in('mes_atual','historico','fca_manifestos'));drop policy if exists operational_admin_insert on storage.objects;create policy operational_admin_insert on storage.objects for insert to authenticated with check(bucket_id='dados-operacionais' and public.is_admin());drop policy if exists operational_admin_update on storage.objects;create policy operational_admin_update on storage.objects for update to authenticated using(bucket_id='dados-operacionais' and public.is_admin());drop policy if exists operational_admin_delete on storage.objects;create policy operational_admin_delete on storage.objects for delete to authenticated using(bucket_id='dados-operacionais' and public.is_admin());
commit;
-- Depois de criar o primeiro usuário:
-- update public.profiles set role='admin',nome='Demétrius Chiesa' where id='UUID_DO_USUARIO';
