import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
export const NEXT_PUBLIC_SUPABASE_URL='https://xgygohmfhyllgfcrgtyu.supabase.co';export const NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY='sb_publishable_Ijcmwt2ZdPa1REDkZrISLA_Rf28weNi';export const STORAGE_BUCKET='dados-operacionais';export const AUTO_REFRESH_MS=300000;const cache=new Map;let db;
export function client(){if(db)return db;if(NEXT_PUBLIC_SUPABASE_URL.startsWith('SEU_'))throw Error('Configure URL e chave pública em supabase.js.');return db=createClient(NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true}})}
export async function signIn(email,password){const{data,error}=await client().auth.signInWithPassword({email,password});if(error)throw error;return data}export const signOut=()=>client().auth.signOut();export const getSession=async()=>(await client().auth.getSession()).data.session;export const authChange=fn=>client().auth.onAuthStateChange((_,s)=>fn(s));
export async function profile(id){const{data,error}=await client().from('profiles').select('id,nome,role').eq('id',id).maybeSingle();if(error)throw error;return data||{id,nome:'Usuário',role:'viewer'}}
async function list(prefix,depth=0){if(depth>4)return[];const{data,error}=await client().storage.from(STORAGE_BUCKET).list(prefix,{limit:1000,sortBy:{column:'name',order:'asc'}});if(error)throw error;let out=[];for(const x of data||[]){const path=`${prefix}/${x.name}`;if(x.id||/\.[a-z0-9]{2,6}$/i.test(x.name))out.push({...x,path});else out.push(...await list(path,depth+1))}return out}
function periodOf(f){const r=f.path.replace(/^historico\//,'');const folder=r.split('/')[0];if(folder!==f.name)return folder;const m=f.name.match(/(20\d{2})[-_. ]?(0?[1-9]|1[0-2])/);return m?`${m[1]}-${String(m[2]).padStart(2,'0')}`:'Histórico'}
export async function periods(){const[cur,hist]=await Promise.all([list('mes_atual'),list('historico')]);const g={};hist.forEach(f=>(g[periodOf(f)]??=[]).push(f));return[{id:'current',label:'Mês atual',origin:'mes_atual',files:cur},...Object.entries(g).sort((a,b)=>b[0].localeCompare(a[0])).map(([k,files])=>({id:'history:'+k,label:k,origin:'historico',files}))]}
const norm=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();async function download(path){const{data,error}=await client().storage.from(STORAGE_BUCKET).download(path);if(error)throw error;return data}async function parse(blob,name){if(/\.csv$/i.test(name)){const text=await blob.text();return await new Promise((ok,fail)=>Papa.parse(text,{header:true,skipEmptyLines:true,complete:r=>ok(r.data),error:fail}))}const wb=XLSX.read(await blob.arrayBuffer(),{type:'array',cellDates:true});return XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:'',raw:false,dateNF:'yyyy-mm-dd'})}
export async function loadPeriod(p){const key=p.id+':'+p.files.map(f=>f.path+':'+(f.updated_at||'')).join('|'),hit=cache.get(key);if(hit&&Date.now()-hit.time<300000)return hit.data;const defs={log:['LOG_MANUTENCAO','LOG MANUTENCAO'],tnps:['tnps','ANL_TNPS'],manifestos:['MANIF_RRS','MANIF RRS']},out={log:[],tnps:[],manifestos:[],files:p.files,missing:[]};await Promise.all(Object.entries(defs).map(async([k,a])=>{const f=p.files.find(x=>a.some(n=>norm(x.name).includes(norm(n))));if(!f)return out.missing.push(a[0]);out[k]=await parse(await download(f.path),f.name)}));cache.set(key,{time:Date.now(),data:out});return out}
export async function listFca(f={}){let q=client().from('fca_manifestos').select('*').order('data_criacao',{ascending:false});if(f.contrato)q=q.ilike('contrato',`%${f.contrato}%`);if(f.manifesto)q=q.ilike('manifesto',`%${f.manifesto}%`);if(f.mes_referencia)q=q.eq('mes_referencia',f.mes_referencia);const{data,error}=await q;if(error)throw error;return data||[]}export async function createFca(p){const{error}=await client().from('fca_manifestos').insert(p);if(error)throw error}export async function updateFca(id,p){const{error}=await client().from('fca_manifestos').update(p).eq('id',id);if(error)throw error}export async function deleteFca(id){const{error}=await client().from('fca_manifestos').delete().eq('id',id);if(error)throw error}
